### ISSUE TITLE
Create Basic Webpage

### ISSUE THREAD

**Issue by pranav-git-hub** [pranav-git-hub/Data-Science#8]
Create a basic webpage displaying projects with the links to this repository. The links and names can easily be found in the README.md file. The webpage can just be a webpage with a list of links and names just as in the readme file's index.

Any enhancements are appreciated.

**Comment by Harshil-Jani** [comment]
@pranav-git-hub Can I create a general WebPage in which you can keep adding new projects in future easily ?

**Comment by pranav-git-hub** [comment]
Ok go ahead.
